/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.AbstractObjekat;
import domen.Clan;
import domen.Paket;
import domen.Pretplata;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.TblModelClanMini;
import model.TblModelPretplata;
import start.KlijentStart;

/**
 *
 * @author vujke
 */
public class PretplataFrm extends javax.swing.JFrame {

    TblModelPretplata tblP;
    TblModelClanMini tblC;
    Clan odabraniClan = null;
    Paket odabraniPaket = null;

    /**
     * Creates new form PretplataFrm
     */
    public PretplataFrm() {
        initComponents();
        jtxtEmail.setEditable(false);
        jtxtEmail.setFocusable(false);
        jtxtImePrezime.setEditable(false);
        jtxtImePrezime.setFocusable(false);
        jtxtPaket.setEditable(false);
        jtxtPaket.setFocusable(false);
        jtxtClanId.setEditable(false);
        jtxtClanId.setFocusable(false);

        srediComboBox();
        srediTabele();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtFilter = new javax.swing.JButton();
        jbtFilter1 = new javax.swing.JButton();
        jtxtClanId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbPaketi = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jbtFilter2 = new javax.swing.JButton();
        jbtFilter3 = new javax.swing.JButton();
        jtxtPretraga = new javax.swing.JTextField();
        jbtOdabrani = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jtxtImePrezime = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtPaket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtEvidentirajUplatu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretplate");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtFilter.setText("Pretraži pretplate");
        jbtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFilterActionPerformed(evt);
            }
        });

        jbtFilter1.setText("Resetuj tabelu");
        jbtFilter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFilter1ActionPerformed(evt);
            }
        });

        jLabel5.setText("ID člana:");

        jcbPaketi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtFilter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtClanId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbPaketi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtClanId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jcbPaketi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtFilter1)
                .addGap(17, 17, 17))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtFilter2.setText("Pretraži članove");
        jbtFilter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFilter2ActionPerformed(evt);
            }
        });

        jbtFilter3.setText("Resetuj tabelu");
        jbtFilter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFilter3ActionPerformed(evt);
            }
        });

        jbtOdabrani.setText("Izaberi člana");
        jbtOdabrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOdabraniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtOdabrani, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtFilter3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtFilter2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFilter2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFilter3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtOdabrani)
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPaketActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime i prezime:");

        jLabel2.setText("e-mail:");

        jLabel3.setText("Paket:");

        jbtEvidentirajUplatu.setText("Evidentiraj ");
        jbtEvidentirajUplatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEvidentirajUplatuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Pretplata se evidentira po današnjem datumu!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtxtImePrezime)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtEvidentirajUplatu, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jtxtPaket))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEvidentirajUplatu)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPaketActionPerformed

    private void jbtFilter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFilter3ActionPerformed
        List<AbstractObjekat> clanovi;
        try {
            // TODO add your handling code here
            clanovi = Kontroler.vratiKontrolera().vratiListuClanova();
            tblC.filterForme(clanovi);
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtFilter3ActionPerformed

    private void jbtOdabraniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOdabraniActionPerformed
        // TODO add your handling code here:
        int red = jTable1.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(rootPane, "Nije odabran član "
                    + "u tabeli!", "Greška!", JOptionPane.ERROR_MESSAGE, null);

            return;
        }

        Clan c = tblC.vratiClana(red);
        odabraniClan = c;
        jtxtImePrezime.setText(c.getIme() + " " + c.getPrezime());
        jtxtEmail.setText(c.getEmail());
        odabraniPaket = (Paket) tblC.vratiPaket(tblC.vratiPaketId(c));
        jtxtPaket.setText(odabraniPaket.toString());
        jtxtClanId.setText(c.getClanId());

    }//GEN-LAST:event_jbtOdabraniActionPerformed

    private void jbtEvidentirajUplatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEvidentirajUplatuActionPerformed
        // TODO add your handling code here:

        if (odabraniClan == null) {
            JOptionPane.showMessageDialog(rootPane, "Nije odabran član! ",
                    "Greška!", JOptionPane.ERROR_MESSAGE, null);
            return;
        }

        Pretplata pre = new Pretplata("0", danasnjiDatum(), odabraniClan, odabraniPaket);

        try {
            Pretplata p = (Pretplata) Kontroler.vratiKontrolera().zapamtiPretplatu(pre);
//            JOptionPane.showMessageDialog(rootPane, "Pretplata nije evidentirana! ",
//                    "Greška!", JOptionPane.ERROR_MESSAGE, null);
            
            JOptionPane.showMessageDialog(rootPane, "Pretplata je evidentirana! ",
                    "Poruka", JOptionPane.INFORMATION_MESSAGE, null);
            
            List<AbstractObjekat> pretplate = Kontroler.vratiKontrolera().vratiListuPretplata();
            tblP.resetTabele(pretplate);
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtEvidentirajUplatuActionPerformed

    private void jbtFilter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFilter2ActionPerformed
        // TODO add your handling code here:
        String pretragaClanova = jtxtPretraga.getText();
        try {
            List<AbstractObjekat> clanovi = Kontroler.vratiKontrolera().pretraziClanove(pretragaClanova);
            tblC.filterForme(clanovi);
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtFilter2ActionPerformed

    private void jbtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFilterActionPerformed
        // TODO add your handling code here:
        Paket pak = (Paket) jcbPaketi.getSelectedItem();
        Clan cln = odabraniClan;
        List<AbstractObjekat> listaPretplata;
//       List<Pretplata> lp = new ArrayList<>();

        try {
            listaPretplata = Kontroler.vratiKontrolera().pretraziPretplate(pak, cln);
//            for (AbstractObjekat abs : listaPretplata) {
//                Pretplata ppppp = (Pretplata) abs;
//                lp.add(ppppp);
//            }
            tblP.resetTabele(listaPretplata);
            
            if (tblP.vratiListu().size() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Ne postoje pretplate"
                        + "za odabranog člana!", "Greška!", JOptionPane.ERROR_MESSAGE, null);
                return;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Postoje pretplate po "
                        + "za odabranog člana!", "Poruka", JOptionPane.INFORMATION_MESSAGE, null);
                
//                
//                JOptionPane.showMessageDialog(rootPane, "Član nije obrisan! "
//                        , "Greška!", JOptionPane.ERROR_MESSAGE, null);
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtFilterActionPerformed

    private void jbtFilter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFilter1ActionPerformed
        try {
            // TODO add your handling code here:

            tblP.resetTabele(Kontroler.vratiKontrolera().vratiListuPretplata());
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtFilter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretplataFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretplataFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretplataFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretplataFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new KlijentStart().start();
                new PretplataFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtEvidentirajUplatu;
    private javax.swing.JButton jbtFilter;
    private javax.swing.JButton jbtFilter1;
    private javax.swing.JButton jbtFilter2;
    private javax.swing.JButton jbtFilter3;
    private javax.swing.JButton jbtOdabrani;
    private javax.swing.JComboBox jcbPaketi;
    private javax.swing.JTextField jtxtClanId;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtImePrezime;
    private javax.swing.JTextField jtxtPaket;
    private javax.swing.JTextField jtxtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediTabele() {
        List<AbstractObjekat> pretplate;
        List<AbstractObjekat> clanovi;
        List<AbstractObjekat> paketi;
        List<AbstractObjekat> listaIp;

        try {

            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            listaIp = Kontroler.vratiKontrolera().vratiListuIP();

            clanovi = Kontroler.vratiKontrolera().vratiListuClanova();
            paketi = Kontroler.vratiKontrolera().vratiSvePakete();

            tblC = new TblModelClanMini(clanovi, listaIp, paketi);
            jTable1.setModel(tblC);
            ///tblP = new TblModelPretplata(pretplate, paketi, clanovi);

            //jTable2.setModel(tblP);
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            pretplate = Kontroler.vratiKontrolera().vratiListuPretplata();
//            paketi = Kontroler.vratiKontrolera().vratiSvePakete();
//            clanovi = Kontroler.vratiKontrolera().vratiListuClanova();
            tblP = new TblModelPretplata(pretplate);

            jTable2.setModel(tblP);
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Date danasnjiDatum() {
        return new Date();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void srediComboBox() {
        List<AbstractObjekat> pakets;
        try {
            pakets = Kontroler.vratiKontrolera().vratiSvePakete();
            jcbPaketi.setModel(new DefaultComboBoxModel(pakets.toArray()));
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        } catch (IOException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PretplataFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
